### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by cajardim** [daimor/vscode-objectscript#38]
- Issue Type: `Performance`
- Extension Name: `vscode-objectscript`
- Extension Version: `0.7.11`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.35.1`

[daimor.vscode-objectscript-unresponsive.cpuprofile.txt](https://github.com/daimor/vscode-objectscript/files/3298410/daimor.vscode-objectscript-unresponsive.cpuprofile.txt

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by daimor** [comment]
Could you please check how is it going now with the latest version?

**Comment by cajardim** [comment]
After updating the latest version the problem no longer occurred, so it is fixed.
