### ISSUE TITLE
More secure way to save server credentials

### ISSUE THREAD

**Issue by nickmitchko** [daimor/vscode-objectscript#39]
It'd be nice to have a more secure way to store server credentials instead of the workspace settings file. An encrypted store or something of the like would be great.

You could do something like wrapping the passphrase and storing it in the connection settings as a hex string.

**Comment by daimor** [comment]
Hi, unfortunately, VSCode itself does not offer yet [any solution](https://github.com/Microsoft/vscode/issues/15414). Until so, I don't see any easy way and good way to do it as well. I'll close it for now but will keep in mind.

Storing as a hex string does not make any sense actually, it will be in a plain text anyway, and where to store passphrase?

**Comment by nickmitchko** [comment]
Sorry, I meant to say was "hash" string. You want the user to login each application opening. Is there not an npm package that does secure credentialing?

**Comment by daimor** [comment]
Anyway, it is not so easy to add, in a way suitable for everyone. Secured storage mostly means some encryption, which then means some secret key. Which should be stored securely and privately and uniquely for each machine where VSCode used. There maybe should be some prompt for the original password, which then can be encrypted and stored, maybe even publicly, but it will be useless for your colleagues for instance, who will need the same access.
So, I'm sure I'll need some time for research on how to do it in a better way. 
You can also do it, and offer as a pull request, if you would like
