### ISSUE TITLE
Export of file results in no file being created

### ISSUE THREAD

**Issue by davbro63** [daimor/vscode-objectscript#41]
**Observation:**
When I create a class (in Studio) and then view that in vsCode I see the code correctly.
With an open folder that is not read only, I export the clsee.
I see the class package directories being created under a 'src' folder but no final .cls file created in the final folder.
Class is a simple:
```
Class User.Test1 Extends %RegisteredObject
{

}
```
$zv for the IRIS env is:
`IRIS for Windows (x86-64) 2019.1 (Build 510U) Thu Mar 14 2019 14:13:37 EDT`

**Comment by daimor** [comment]
Could you share Output log?

**Comment by davbro63** [comment]
I don't see anything relevant in the Log window (all 4 of them)

**Comment by daimor** [comment]
So, ObjectScript output, completely empty?
I expect to see at least an error

**Comment by davbro63** [comment]
I found what you are asking for now:
[image: image.png]

Is that what you are looking for ?

**Comment by daimor** [comment]
I don't see any images, could you repost it?

**Comment by davbro63** [comment]
In text form:
export "User.Test1.cls" as "d:\temp\src\User\Test1.cls" - ERROR: Error:
Failed to load page "/api/atelier/v3//doc/User.Test1.cls", status code: 404
Exported items: 0
Items failed to export:
User.Test1.cls - Error: Failed to load page
"/api/atelier/v3//doc/User.Test1.cls", status code: 404
export "User.Test1.cls" as "d:\temp\src\User\Test1.cls" - ERROR: Error:
Failed to load page "/api/atelier/v3//doc/User.Test1.cls", status code: 404
Exported items: 0
Items failed to export:
User.Test1.cls - Error: Failed to load page
"/api/atelier/v3//doc/User.Test1.cls", status code: 404
export "User.Test1.cls" as "d:\temp\src\User\Test1.cls" - ERROR: Error:
Failed to load page "/api/atelier/v3//doc/User.Test1.cls", status code: 404
Exported items: 0
Items failed to export:
User.Test1.cls - Error: Failed to load page
"/api/atelier/v3//doc/User.Test1.cls", status code: 404

**Comment by daimor** [comment]
Thanks, I think it gives what I need. I'll fix it.

**Comment by daimor** [comment]
Looks like you have an empty value in setting "objectscript.conn.ns", could you confirm that?
It is not actually allowed so. And such error expected in this case.

**Comment by daimor** [comment]
And if you have empty ns in settings you used action view another namespace in the explorer and tried to export some class. So, I fixed export from another namespace and added confirmation for it.
Just for clarification, when you will get a local copy of classes, then after edit it will save and compile in namespace specified in settings.

So, anyway if you have empty ns in your settings by now, you should fill it with a correct value, and everything will work as expected.

**Comment by davbro63** [comment]
I did have an empty namespace.
I did that as the initial namespace I wanted to use did not show up in the
'open other namespace' - when I left it as blank it did show.
I'll add the namespace back
Thanks for your help

**Comment by davbro63** [comment]
Still nothing:
settings are:
"objectscript.conn": {
        "active": true,
        "label": "Local",
        "host": "127.0.0.1",
        "port": 52773,
        "username": "xxxxx",
        "password": "xxxxx",
        "ns": "%SYS",
        "https": false
    },
    "objectscript.conn.ns": "%SYS"

On export I now see
export "User.Test1.cls" as "d:\temp\src\User\Test1.cls" - ERROR: Error:
Failed to load page "/api/atelier/v3/%25SYS/doc/User.Test1.cls", status
code: 404
Exported items: 0
Items failed to export:
User.Test1.cls - Error: Failed to load page
"/api/atelier/v3/%25SYS/doc/User.Test1.cls", status code: 404

**Comment by daimor** [comment]
yes, this happens, because, you set namespace as %SYS, but trying to export from another namespace, USER in your case. Export from another namespace will work only with the next release.
You should set USER to ns, and it will work.

**Comment by davbro63** [comment]
It worked - thanks

**Comment by davbro63** [comment]
Probably a separate bug, however when I hover above a command / intrinsic
function ($get etc.) I see the information display - nice work.
Hover over a non-word and the log shows
[2019-07-02 10:02:15.770] [exthost] [error] TypeError: Cannot read property
'end' of undefined
at ObjectScriptHoverProvider.dollars
(c:\Users\Administrator\.vscode\extensions\daimor.vscode-objectscript-0.7.11\out\providers\ObjectScriptHoverProvider.js:25:133)

Reviewing the typescipt I see:
public dollars(document: vscode.TextDocument, position: vscode.Position):
vscode.ProviderResult<vscode.Hover> {
    const word = document.getWordRangeAtPosition(position);
    const text = document.getText(
      new vscode.Range(new vscode.Position(position.line, 0), new
vscode.Position(position.line, *word.end*.character)),
    );

Probably needs some defensive coding around the word object before it's
used.
