### ISSUE TITLE
Incorrect errors being reported

### ISSUE THREAD

**Issue by d-wilks** [daimor/vscode-objectscript#49]
The latest update is causing errors to be displayed for lass and dynamic queries.  However the class is still able to be successfully compiled:

![image](https://user-images.githubusercontent.com/8263236/63813031-73067f00-c96b-11e9-9312-4bbc9d10f1d1.png)

![image](https://user-images.githubusercontent.com/8263236/63813051-874a7c00-c96b-11e9-9cd5-196c46090c38.png)

![image](https://user-images.githubusercontent.com/8263236/63813535-2328b780-c96d-11e9-8b98-095ddaf14766.png)

**Comment by daimor** [comment]
Sorry, yes, it just goes from one new feature added with the latest version. It works quite dumb, yet, but will be fixed in the near future.
