### ISSUE TITLE
ObjectScript Explorer does not show "GeneratedBy" classes (e.g. REST disp)

### ISSUE THREAD

**Issue by albertoft** [daimor/vscode-objectscript#52]
ObjectScript Explorer does not show classes marked with "GeneratedBy"

I've created a new REST application from OpenAPI spec. using %REST.
This generates 3 classes: spec, impl, disp.
Disp (dispatcher) class is not shown on ObjectScript Explorer.

Class that is not shown is like:
`Class Test.API.DemoV1.disp Extends %CSP.REST [ GeneratedBy = Test.API.DemoV1.spec.cls, ProcedureBlock ]`

If you remove `GeneratedBy = Test.API.DemoV1.spec.cls` and compile, then the class is shown in Explorer.

There is any way to display these kind of classes?
(I've already tried setting "Export: Generated" setting)

**Comment by daimor** [comment]
Yes, generated classes hidden by default, so, you can't see them there. But they should be available by command View Others on original class.

**Comment by albertoft** [comment]
Thanks! Resolved
