### ISSUE TITLE
Wrong recognizing of SQL commands in Query methods

### ISSUE THREAD

**Issue by MakarovS96** [daimor/vscode-objectscript#55]
VSCode mark these commands as unrecognized
v0.7.13

![image](https://user-images.githubusercontent.com/19629483/65132566-d5eab380-da09-11e9-9f95-08734f8fb8dc.png)
![image](https://user-images.githubusercontent.com/19629483/65132574-d7b47700-da09-11e9-849b-8b3079332c90.png)

**Comment by daimor** [comment]
Yes, it's a new feature added in the latest version, which is actually quite dumb yet. 
It checks commands and system functions.
But, it can't recognize SQL or any other language, yet, but in the future it will.
