### ISSUE TITLE
"Compile successed" is incorrect grammar

### ISSUE THREAD

**Issue by henryvincent96** [daimor/vscode-objectscript#58]
Hello - absolutely love this plugin - just a little nitpick here.
When compilation succeeds, the notification pops up:
![successed](https://user-images.githubusercontent.com/18680921/66925054-a7b9bd00-f023-11e9-817f-2410b9af4ec5.png)
The problem is that "successed" is not a word in english - it should probably be "Compilation succeeded" or something like that.

**Comment by daimor** [comment]
Thanks ))

Btw, you can disable these messages by config `objectscript.suppressCompileMessages: "true"`
