### ISSUE TITLE
ODBC error creating new connection

### ISSUE THREAD

**Issue by davidpeterunderhill** [daimor/vscode-objectscript#59]
Hello,
I have installed the VSCode (1.39.2) on windows 10 and the ObjectScript extension (0.7.13) then configured the settings.json with my connection details including a valid username and password with the %ALL role to connect to
> $zv=Cache for Windows (x86-64) 2018.1.2 (Build 309_5) Wed Jun 12 2019 20:14:50 EDT
>
The status bar says connected but when I try to open out the namespace explorer view I get the error
> ERROR #5540: SQLCODE: -99 Message: User UnknownUser is not privieged for the operation
>
There are no entries in the ObjectScript output window.

![image](https://user-images.githubusercontent.com/36628548/67013164-97204a00-f0ea-11e9-97ac-0ecb0d08c0ad.png)

**Comment by davidpeterunderhill** [comment]
A quick update, exporting via CTRL+SHIFT+P works despite this error.

**Comment by daimor** [comment]
Please, could you try with the latest beta release which you can find [here](https://github.com/daimor/vscode-objectscript/releases).  
You can install it manually then, by the command `Install from VSIX...`

**Comment by davidpeterunderhill** [comment]
I have tested with a local IRIS instance and it works without an error, this only seems to be an issue connecting to Cache.

> 
> 
> Please, could you try with the latest beta release which you can find [here](https://github.com/daimor/vscode-objectscript/releases).
> You can install it manually then, by the command `Install from VSIX...`

**Comment by davidpeterunderhill** [comment]
> 
> 
> Please, could you try with the latest beta release which you can find [here](https://github.com/daimor/vscode-objectscript/releases).
> You can install it manually then, by the command `Install from VSIX...`

Thanks, I'll test this tomorrow and let you know.

**Comment by davidpeterunderhill** [comment]
Actually got a chance to test before I left and this works perfectly now.
Thatnks for the help.
