### ISSUE TITLE
Compiling a complete package 

### ISSUE THREAD

**Issue by ayalros** [daimor/vscode-objectscript#69]
Hi,
In our dep, there is a need to compile complete packages, rather then only single files.
It will be wonderful if you could add it.

Regards,

**Comment by daimor** [comment]
A the moment I see only one place where I can put it. In the Server Explorer View.
It is also supported already by now, to compile with custom flags. Just set in settings as default, or with an extra command. So, you can add the flag `b` for instance

b | Includes subclasses and classes that reference the current class in SQL usage.
-- | --

And anyway it looks like you need some changes in classes if you often need package compilation. It can be actually fixed when using correct flags in classes and correct dependencies and so on.

**Comment by daimor** [comment]
Just published the latest beta release [here](https://github.com/daimor/vscode-objectscript/releases). You can install it manually, with Install from VSIX command in VSCode. Could you try it?
