### ISSUE TITLE
Goto definition opens new read only version

### ISSUE THREAD

**Issue by bourette** [daimor/vscode-objectscript#71]
When using F12 Go to Definition it opens a ReadOnly version of the class even when the method is in the same class.  When editing code, I wish that I had the option for the cursor to just go to the method instead of spawning a new edit window.

**Comment by daimor** [comment]
It was actually quite tricky how to convert class name to filename, so I used export settings, for this task. You need to have clear folder structure of files as configured in `objectscript.export` settings. To check these settings, you can use Export action from Server explorer view. When it will be correctly configured all navigation will work well.

**Comment by bourette** [comment]
I'm not sure I'm following.  I've defined

{
	"name": "interopTools",
	"path": "/Volumes/P4/projects/ProductionGenerator/databases/enslib/packages/InteropTools"
},
{
	"uri": "isfs://interopTools",
	"name": "itServer"
},

Why isn't that enough to determine the structure?  I tried various attempts at 

I was getting
EnsLib.InteropTools.HL7.Setup.cls - Error: EACCES: permission denied, mkdir '//src/'

So I attempted 
	"objectscript.export.folder": "/Volumes/P4/",
And export produced 
export "EnsLib.InteropTools.HL7.Setup.cls" as "///Volumes/P4//EnsLib/InteropTools/HL7/Setup.cls" - Success 
Exported items: 1
export "HS.HC.Info.mac" as "///Volumes/P4//HS/HC/Info.mac" - Success 
Exported items: 1

I'm not following how I would set this up.  How would classes end up in one folder and routines in another?   Everything works except for the Go to Definition.

**Comment by daimor** [comment]
Ahh, ok, you have virtual fs, so, this tip would not help you. 
In your case would help to add setting `objectscript.serverSideEditing`
```JSON
{
	"folders": [
		{
			"name": "interopTools",
			"path": "/Volumes/P4/projects/ProductionGenerator/databases/enslib/packages/InteropTools"
			},
			{
			"uri": "isfs://interopTools",
			"name": "itServer"
			}
	],
	"settings": {
		"objectscript.serverSideEditing": true
	}
}
```

**Comment by bourette** [comment]
Sorry, I did setup a virtual fs, but only to get access to generated code.

**Comment by daimor** [comment]
Generated code you can see by command View Others with shortcut Ctrl+Shift+V as in Studio

**Comment by bourette** [comment]
I took out the uri and updated 
   "objectscript.export.folder": "",

export "EnsLib.InteropTools.HL7.DG.cls" as "/Volumes/P4/projects/ProductionGenerator/databases/enslib/packages/InteropTools//EnsLib/InteropTools/HL7/DG.cls" - Success 
Exported items: 1

Everything is correct except this should be in the cls sub folder because it's a class, but if I make "objectscript.export.folder": "cls", a routine export ends up in the wrong folder.

**Comment by daimor** [comment]
`"objectscript.export.addCategory": true` should help with `cls` folder

**Comment by bourette** [comment]
Yes, that resolves the go to definition issue, thanks!
