### ISSUE TITLE
Problem connecting to IRIS on CentOS7

### ISSUE THREAD

**Issue by uleimberger** [daimor/vscode-objectscript#74]
I have a problem connecting to IRIS running on a CentOS7.
VSCode running on a Windows 10 Desktop.
I can connect to Studio or Terminal via IRIS client on my Windows and work with the user udo/udo.
So there should not be any security issue.

Here are my Extension parameters:
    "objectscript.autoPreviewXML": true,
    "objectscript.conn.active": true,
    "objectscript.conn.label": "COS7",
    "objectscript.conn.ns": "DEVELOP",
    "objectscript.conn.port": 52773,
    "objectscript.conn.password": "udo",
    "objectscript.conn.username": "udo",
     "objectscript.conn.host": "centos7.local"

where udo is a super user.
The extension try to connect but get no Connect but rather only ERROR in the status line. No hint what causes the error.
![image](https://user-images.githubusercontent.com/1407860/69739239-637f0980-1105-11ea-95aa-068969517815.png)
I can open the Management Portal via the Link offered by VSCode-Extension:
http://centos7.local:52773/csp/sys/UtilHome.csp?$NAMESPACE=DEVELOP
and log in with user udo/udo but I am not able to connect to IRIS database in namespace DEVELOP.
How can i figure out what's going on ? Enabling audit on IRIS does not give me any hint.

**Comment by daimor** [comment]
Udo, can you show whats written in View > Output > dropdown:ObjectScript

**Comment by uleimberger** [comment]
Cool. As I am new to VSCode - I did not know this.
Now it's clear:
Authorization error: please check your username/password in the settings,
            and if you have sufficient privileges on the server.
But how can this be? I can log in via IRIS Studio or IRIS Terminal? And 'udo' is a super user.

**Comment by daimor** [comment]
Can you try to open such URL in the browser?
http://centos7.local:52773/api/atelier/
It should offer to enter login/pass and then show some JSON.

Also, could you try the latest beta [release](https://github.com/daimor/vscode-objectscript/releases)?

**Comment by uleimberger** [comment]
After going to http://centos7.local:52773/api/atelier/ it ask me for username and password - but either udo/udo nor _SYSTEM/SYS works. Is there a license problem ?

**Comment by daimor** [comment]
If you don't have any license there, it will not be possible to connect.
You need any license, on WRC you can find a preview license, which will give you the ability to connect.
If you have a license, but still do not able to connect, check the license usage on System Management Portal.

**Comment by daimor** [comment]
IRIS Community Edition, should work without any licenses, it's already included inside.

**Comment by uleimberger** [comment]
Yes i thought so too. Let's close this ticket and discuss on my threat on Intersystems Community. Thank you so much for your hard work and tipps.
