### ISSUE TITLE
Issue with code not loading on save

### ISSUE THREAD

**Issue by bourette** [daimor/vscode-objectscript#76]
I'm having an issue with one folder in my project not loading the code when I save a modification.  If I use load and compile it works fine, other functions like view other also work and other folders in the project also work fine.  There is no output in the ObjectScript log window or in Extension Host log window.  How do I diagnose what is happening?  
BTW this was working fine last week (I'm running 0.7.14 beta 4) I'm just not sure what tweak I have done to break it ;)

**Comment by daimor** [comment]
Very interesting. Just to be sure, does not folders/classnames contain percent sign?

**Comment by bourette** [comment]
No, no percent signs.

**Comment by daimor** [comment]
Did not install Serenji extension, this extension may block some of my features?
You can try to disable any other extensions.

**Comment by bourette** [comment]
No I have not installed any new extensions.  Also, to re-iterate, most folders are working, it's just this one group.

**Comment by daimor** [comment]
Would it be possible to rename/copy and check how it works?

**Comment by bourette** [comment]
Very interesting, yes a copy to a new location works.

**Comment by bourette** [comment]
Any thoughts on what might be causing this or how to resolve it?

**Comment by daimor** [comment]
I think the best way would be to look at all levels of VSCode settings, user, workspace, folder.
And find something, that would mention this name of a folder.

**Comment by bourette** [comment]
I have gone through all the settings, I even renamed the folder, I disabled all extensions, I removed all other folders.  Is there any way to log what's happening during the save?

**Comment by daimor** [comment]
Would it be possible to make some small example where your issue reproduced, and I can try to do it by myself?
Or you can try to debug it by yourself, just by cloning this repo, and run it in debugging.

**Comment by bourette** [comment]
It appears as though the issue is related to the fact that there is source control setup on the server.  If I have not executed our build script, the editor works fine, pushing the changes and compiling.  We have a build script which loads from multiple packages and defines source control, once that has been executed, the source files no longer automatically compile on the server on save, the changes do get pushed up to the server, but not compiled.  I thought for sure this was working.  If I copy the same source to another directory and edit there it is pushed up and compiled.

Was I just mistaken in thinking this was working?

**Comment by daimor** [comment]
So, if you have Studio Source Control class, it can block some actions. There are some flags, like checked out, read-only and so on. Unfortunately, I don't have any options to disable SourceControl class when using VSCode. So, you can do it manually for yourself.

**Comment by bourette** [comment]
Well, I'm not sure we're on the same page.  The save moves the code to the server just doesn't compile it and therefore doesn't give the compiled successfully dialog.  I can also use import and compile (command F7) without issue.  The class is checked out in source control.

**Comment by bourette** [comment]
I loaded up https://github.com/daimor/vscode-objectscript/releases/tag/v0.7.14-beta.2 and restarted VS code and this problem goes away.  I tried to reproduce a sample but have not been able to so far.  To date I have not tried to debug the code.

**Comment by daimor** [comment]
That's very good

**Comment by bourette** [comment]
Good?  It's broken in beta.4, that's when I started running into trouble.

**Comment by daimor** [comment]
yep, just missed version you mentioned.
so, beta.5 and beta.3 also not working?

**Comment by bourette** [comment]
Correct, it appears it stopped working with beta 3.

**Comment by daimor** [comment]
Is it possible to make a small reproducible example?

**Comment by bourette** [comment]
No, I haven't been able to do that, every attempt to produce the situation does not reproduce the issue.    

The interesting thing to note (again) is that a change is saved to the server, but the class does not compile.  I know this because if I export the class, the change exists.

**Comment by daimor** [comment]
Well, I think, I got what's happening.
Some time ago, I've fixed the issue, when the error happened during saving on a server side, was with error, but with a quite strange error. And class still compiled when should not. So, now I can catch it and do not compile class if something goes wrong. But the error should go output view anyway.

So, can you send some request manually with curl or postman.
Something like this.
In this case error in duplicated classmethod name
![image](https://user-images.githubusercontent.com/1212251/70468122-8f23cb80-1ad7-11ea-9f34-d8bfb181d70e.png)
API returns status code as 200 OK, empty `console`,  but `result.status` contains some error.
I check this value now and send any non-empty value to Output view, and do not compile such class.

**Comment by bourette** [comment]
I found the issue.  I realized that when I went back to beta.3 the go to definition stopped working and that you had pointed me to the export.folder to resolve this.  I at some point in my cleanup had updated the export.folder but I guess I hadn't hit the refresh and was using the old settings until my restart.
