### ISSUE TITLE
Unrecognized command errors inside multiline comments /**/ - similar to #36 

### ISSUE THREAD

**Issue by toncatgm** [daimor/vscode-objectscript#84]
Similar to #36

Both indented words, Incoming and Outgoing, in this multiline comment example are highlighted as errors:
Unrecognized command [line,column]
"Command 'Incoming' not recognized" and Command 'Outgoing' not recognized":
/*
	Incoming data.
	Outgoing data.
*/

This example, when first word in line is in column 1, does not cause errors:
/*
Incoming data.
Outgoing data.
*/

**Comment by daimor** [comment]
I'm sure I've alerady fixed it. Could you check with the latest beta [release](https://github.com/daimor/vscode-objectscript/releases).

**Comment by toncatgm** [comment]
Thanks and well done Dmitry,

0.7.14-SNAPSHOT fixes this issue as well as #84!

For your information in case you are not aware of the Buffer() deprecation warnings: 
$ code --install-extension vscode-objectscript-0.7.14-B20200104.vsix
Installing extensions...
(node:17860) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:17860) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Extension 'vscode-objectscript-0.7.14-B20200104.vsix' was successfully installed.
UKMBPABEUKES:vscode-objectscript-pre-release abeukes$ 

Regards
Tony

**Comment by daimor** [comment]
Yeah, I see those warnings as well, but issues comes from some dependencies
