### ISSUE TITLE
Tree structure problem with v0.7.14-B20200113

### ISSUE THREAD

**Issue by bourette** [daimor/vscode-objectscript#86]
When setup with server side source control, the tree appears have some sort of recursive problem where HealthConnect has 
HS
 ./EnsHL7
 ./EnsLib
 ./HS
 ./HSMOD
So it shouldn't have these items inside HS and the items expected there are missing.  Moving back to 0.7.14-B20200109.vsix resolves these issues.

I really like the csp editing though!  Keep up the good work!

**Comment by daimor** [comment]
Thanks, fixed, you can check it with the latest beta release
