### ISSUE TITLE
Update has caused my connection to fail

### ISSUE THREAD

**Issue by henryvincent96** [daimor/vscode-objectscript#87]
When I reloaded my VSCode today my connection failed, and now nothing will compile. There are also these new settings about docker compose - the one about the internal port number is showing an error.
We don't use docker compose - how can I get it working the way is was?

**Comment by daimor** [comment]
Hi, sorry about that, it was work by ignoring docker-compose, if nothing defined there as by default
could you should your settings, and how output looks like

**Comment by henryvincent96** [comment]
These are the relevant settings in my settings.json:
```
"objectscript.compileFlags": "cbuk",
"objectscript.autoCompile": true,
"objectscript.conn.active": true,
"objectscript.conn.ns": "LOCALDEV"
```
I'm not sure what you mean by my output, sorry - what do I need to show you?

**Comment by daimor** [comment]
Menu View -> Output, dropdown=Objectscript

**Comment by henryvincent96** [comment]
Ah okay:
![image](https://user-images.githubusercontent.com/18680921/72719814-801d4800-3b70-11ea-8bc2-291062bcd53c.png)

**Comment by daimor** [comment]
Ahh, sorry, I've changed default port from 57772 (Caché) to 52773 (IRIS)
so, you just have to specify port

**Comment by henryvincent96** [comment]
Okay great that fixed it - thanks very much for the quick response!

**Comment by evshvarov** [comment]
> Ahh, sorry, I've changed default port from 57772 (Caché) to 52773 (IRIS)

I think it makes sense to announce the change in the Release notes on
Developers Community

**Comment by daimor** [comment]
Yep, for sure
