### ISSUE TITLE
Studio Source Control is gone in v0.8.2-beta.1

### ISSUE THREAD

**Issue by mat1990dj** [daimor/vscode-objectscript#98]
I'm no longer able to open the studio actions menu in latest versions.

**Comment by mat1990dj** [comment]
Actually, in 0.8 it also happens :(

**Comment by daimor** [comment]
Studio actions, should be available for `isfs://` files, so, could you check if you open it there?

**Comment by mat1990dj** [comment]
When you talk about isfs you mean accessing classes from the plugin section, right? (Server classes)
I'm seeing this right now:
![image](https://user-images.githubusercontent.com/5220059/75544387-1d975180-5a24-11ea-8413-11ac41bfe023.png)

This is my config:
{
  "objectscript.conn.ns": "ACB",
    "objectscript.conn.password": "INFINITY",
    "objectscript.serverSideEditing": true,
    "objectscript.conn.label": "DEV",
    "objectscript.conn.active": true,
    "objectscript.conn.port": 57772,
    "objectscript.conn.docker-compose.internalPort": 57772,
    "objectscript.conn.docker-compose.service": "DEV"
  }
Not using docker.

**Comment by daimor** [comment]
I mean virtual filesystem, for [server-side editing](https://github.com/daimor/vscode-objectscript/wiki/Server-side-editing). It was added only there at the moment.

**Comment by mat1990dj** [comment]
Ok
